vich_uploader:
    db_driver: orm
    mappings:
        product_image:
            uri_prefix: /img/products
            upload_destination: '%kernel.project_dir%/public/img/products'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
